### ISSUE TITLE
vmproxy use

### ISSUE THREAD

**Issue by albertog** [ronoaldo/aetools#6]
Hi firstly I give you thanks for your great tools. I would like used it  but I have a doubt about how should I use this vmproxy with dispacht.yaml similar that vm standard or other away. 
I have tried but connections is refused probably I am doing some wrong.

Can you provided a link or example that I can read.

thanks in advance.

**Comment by ronoaldo** [comment]
Hi @albertog! Thanks for the heads up. Please try this steps:
1. First, make sure that your VM is properly running. This can be done by clicking on the VM IP address in the instances list on Developers Console. If you get the proper response, then your VM is properly up and running.
2. If your VM is not running, SSH into it and investigate if your backend software is up, and it is listening to the 0.0.0.0 IP; if your program in the VM listen only to localhost, it will not work.
3. Check the Cloud Logging logs, filtering by the App Engine version you deployed, you should see some info there that could help. Post it on a gist (after you remove any confidential information) and share it here so we may take a look.

It will help also if you can share what software you are running in the VM. In regards to the dispatch.yaml file, that should work just fine.

Finally, please keep in mind that vmproxy was designed to handle non-scaling traffic, i.e., it is designed to allow you to spin up on-demand VMs, but you need to shut them down on you code and it won't scale by design. It may be easier depending of your use case that you could try the beta Managed VMs, that has more features and scales up and down (except scaling to zero).

You can find examples in the vmproxy/examples folder. Doing minor changes in this app should get you started.

Let me know if that helps!

**Comment by albertog** [comment]
Ok got it now is more clear. it is working and it is better than i tought now that I understand the phylosophy of design.

Again thanks and I wil encourage to improve/maintenace becasue it is a really useful.

Bye
